export const copy = {
  app: {
    title: "NeoTaste — Two-user demo",
    subtitle: "Gift a deal (with a note) or invite up to 3 friends to dine.",
  },
  tabs: {
    home: "Home",
    feed: "Feed",
    discover: "Discover",
    bookings: "Bookings",
    profile: "Profile",
  },
  bookings: {
    title: "Bookings",
    upcoming: "Upcoming",
    history: "History",
    empty: "No bookings yet.",
    historyEmpty: "Your redeemed and cancelled bookings will show up here.",
    saved: (amount) => `${amount}€ saved`,
    cancelled: "Cancelled",
    bookAgain: "Book again",
    writeReviewTitle: (name) => `Rate your visit to ${name}`,
    writeReviewSubtitle: "Tap a star to rate.",
    writeReviewHowLabel: "How was it?",
    writeReviewPlaceholder: "Share your experience.",
    writeReviewSubmit: "Post review",
    writeReviewContinue: "Continue",
    redeemedToast: (name) => `${name} redeemed your deal`,
    redeemedNotification: "{name} redeemed your deal",
    leaveReview: "Leave a review",
    recommendedTitle: "You recommended this",
    recommendedSubtitle: (count) =>
      count === 1 ? "Sent to 1 friend" : `Sent to ${count} friends`,
    recommendedMessageLabel: "Your message",
    recommendedNoMessage: "No message attached.",
  },
  dealCard: {
    bookDeal: "Book deal",
    bookedAt: (dateLabel, timeWindow) =>
      `${dateLabel.toLowerCase()} ${timeWindow}`,
    youllLove: "You'll love this!",
    avg: (price) => `Avg. ${price}`,
  },
  redeem: {
    close: "Close",
    back: "Back",
    slide: "Slide to Redeem",
    now: "NOW",
    valid: "VALID",
    redeemedAt: "REDEEMED AT",
    saveTitle: "How much did you save?",
    saveCurrency: "€",
    continue: "Continue",
    rateTitle: (restaurantName) => `Rate your visit to ${restaurantName}`,
    rateSubtitle: "Tap a star to rate.",
    ratedTitleGood: "Glad you liked it!",
    ratedTitleOk: "Thanks for the feedback!",
    // Inline "thank the people who got you here" inside the rate sheet —
    // avatars + checkmark toggle, default all selected.
    thankLabel: "Thank the friends who got you here",
    reviewLabel: "How was it?",
    reviewPlaceholder: "Share your experience.",
    photosLabel: "Add photos",
    photosBadge: "New",
    photosHint: "Attach up to 10 photos to your review.",
    postReview: "Post review",
    // Recommend-to-friends step (replaces the standalone credit step).
    recommendTitle: "Recommend to friends",
    recommendSubtitle: "Send this deal to friends who'd love it.",
    recommendMessageLabel: "Add a personal message",
    recommendPlaceholder: "Why do you recommend it?",
    recommendSend: "Send recommendation",
    recommendDone: "Done",
    redeemingWithOne: "Redeeming with 1 friend",
    redeemingWith: (n) => `Redeeming with ${n} friends`,
    recommendPickTitle: "Recommend to…",
    recommendPickDone: (n) =>
      n === 0 ? "Done" : n === 1 ? "Done · 1 friend" : `Done · ${n} friends`,
    recommendPickFriends: "Pick friends to recommend to",
    recommendNoneSelected: "No one selected",
    friendCountOne: "1 friend",
    friendCount: (n) => `${n} friends`,
  },
  bookingConfirmation: {
    title: "Confirm booking",
    subtitle: "Review the deal before locking it in.",
    dateLabel: "Date",
    timeLabel: "Time",
    defaultDate: "Today",
    defaultTime: "19:00 – 22:00",
    note: "This is a placeholder for the booking flow. Picking the time slot, party size and payment would happen here.",
    confirm: "Confirm booking",
    close: "Close",
  },
  recommendations: {
    title: "Recommendations",
    subtitle: (count) =>
      count === 1
        ? "1 friend recommends this"
        : `${count} friends recommend this`,
    empty: "No recommendations yet.",
  },
  userDetail: {
    followers: "Followers",
    following: "Following",
    follow: "Follow",
    followingBtn: "Following",
    reviews: "Reviews",
    lists: "Lists",
    emptyReviews: "No reviews yet.",
    emptyLists: "No lists yet.",
    listCountOne: "1 spot",
    listCount: (n) => `${n} spots`,
    saveList: "Save list",
    listBy: (name) => `${name}`,
    listSavedBy: (count) => `bookmarked by ${count}`,
    friendsBadge: "Friends",
    friendsOnly: "Friends only",
    visited: "Visited",
    yourListsHeader: "Your lists",
    savedListsHeader: "Bookmarked",
  },
  detailPage: {
    open: "Open",
    closesAt: (time) => `Closes at ${time}`,
    distance: (km) => `${km} km`,
    reviews: "Reviews",
    overview: "Overview",
    about: "About",
    deals: "Deals",
    info: "Info",
    seeAllReviews: "See all reviews",
    timeAgo: (daysAgo) => {
      if (daysAgo < 1) return "today";
      if (daysAgo === 1) return "1 day ago";
      if (daysAgo < 7) return `${daysAgo} days ago`;
      if (daysAgo < 14) return "1 week ago";
      if (daysAgo < 30) return `${Math.floor(daysAgo / 7)} weeks ago`;
      if (daysAgo < 60) return "1 month ago";
      return `${Math.floor(daysAgo / 30)} months ago`;
    },
    timeAgoShort: (daysAgo) => {
      if (daysAgo < 1) return "today";
      if (daysAgo === 1) return "1d ago";
      if (daysAgo < 7) return `${daysAgo}d ago`;
      if (daysAgo < 14) return "1w ago";
      if (daysAgo < 30) return `${Math.floor(daysAgo / 7)}w ago`;
      if (daysAgo < 60) return "1mo ago";
      if (daysAgo < 365) return `${Math.floor(daysAgo / 30)}mo ago`;
      return `${Math.floor(daysAgo / 365)}y ago`;
    },
    actions: {
      menu: "Menu",
      location: "Location",
      save: "Save",
      share: "Share",
    },
  },
  bookingCard: {
    actions: {
      location: "Location",
      share: "Share",
      cancel: "Cancel",
      support: "Support",
    },
    redeem: "Redeem deal",
    goingWith: "Going with",
    gifted: (name) => `${name}'s gift`,
    gift: "Gift this deal",
    addCrew: "Add to crew",
  },
  picker: {
    giftTitle: "Send as a gift",
    giftSubtitle: "Pick a friend to receive this deal.",
    dineTitle: "Invite to dine",
    dineSubtitle: "Pick up to 3 friends to invite.",
    searchPlaceholder: "Search friends",
    empty: "No friends found.",
    close: "Close",
    back: "Back",
    memberLabel: "NeoTaste Member",
    maxReached: (max) => `Max ${max} friends`,
    continue: (n) => (n > 0 ? `Continue (${n})` : "Continue"),
    sendToPhone: "Send to a phone number",
    sendToPhoneDesc: "They'll get an SMS to redeem.",
  },
  phone: {
    title: "Send via SMS",
    subtitle: "They'll receive an SMS with a link to redeem on NeoTaste.",
    placeholder: "+49 123 456 7890",
    label: "Phone number",
    continue: "Continue",
    invalid: "Enter a phone number to continue.",
    invalidFormat: "Enter a valid phone number (7-15 digits, optional +).",
    recipientLabel: "Sending to phone",
    quota: (remaining, total) => `${remaining} of ${total} SMS gifts left`,
    quotaReached: "You've used all your SMS gifts.",
  },
  message: {
    giftTitle: (name) => `Send ${name} a gift`,
    inviteTitle: (count) =>
      count > 1 ? `Invite ${count} friends` : "Invite to dine",
    sendingToGift: "Sending to",
    sendingToDine: "Inviting",
    change: "Change",
    messageLabel: "Add a personal message",
    messageHint: "Leave blank to skip.",
    placeholderGift: "Enjoy your dinner! You'll love this!",
    placeholderDine: "Let's meet at 7. See you there!",
    sendGift: "Send gift",
    sendInvitation: "Send invitation",
  },
  toast: {
    giftReceived: (name) => `${name} sent you a deal`,
    dineReceived: (name) => `${name} invited you to a deal`,
    thankReceived: (name) => `${name} thanked you`,
    recommendReceived: (name) => `${name} recommends a deal`,
    giftSent: (recipient) => `Gift sent to ${recipient}`,
    dineSent: (who) => `Invited ${who}`,
    thankSent: (who) => `Thanked ${who}`,
    recommendSent: (who) => `Recommendation sent to ${who}`,
    redeemedReceived: (name) => `${name} redeemed your deal`,
    peopleCount: (count) => `${count} people`,
    dismiss: "Dismiss",
  },
  invitations: {
    sectionTitle: "Invitations",
    invitedYou: "invited you to a deal",
    accept: "Accept",
    decline: "Decline",
  },
  notifications: {
    button: "Notifications",
    title: "Notifications",
    subtitle: "Recent activity from your friends.",
    empty: "No notifications yet.",
    bookDeal: "Book a deal",
    seeBookings: "See bookings",
    seeInformation: "See information",
    writeReview: "Write review",
    giftReceived: (name) => `${name} sent you a gift`,
    giftSent: (name) => `You sent ${name} a gift`,
    giftSentToPhone: (phone) => `You sent a gift to ${phone}`,
    dineInvited: (name) => `${name} invited you to a deal`,
    dineSent: (name) => `Waiting for ${name} to accept`,
    dineJoined: (name) => `You joined ${name}'s deal`,
    dineAccepted: (name) => `${name} accepted your invitation`,
    // Templates with {name} / {phone} placeholders. The placeholder
    // segment is rendered in bold by NotificationCard.
    tpl: {
      giftReceived: "{name} sent you a gift",
      giftSent: "You sent {name} a gift",
      giftSentPhone: "You sent a gift to {phone}",
      dineInvited: "{name} invited you to a deal",
      dineSent: "Waiting for {name} to accept",
      dineJoined: "You joined {name}'s deal",
      dineAccepted: "{name} accepted your invitation",
      thankReceived: "{name} thanked you for the recommendation",
      recommendReceived: "{name} recommends a deal",
      redeemedReceived: "{name} redeemed your deal",
    },
  },
};
